name: Check code & push to Docker Hub
on: push
jobs:
  check_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build image
        run: sudo docker build -t html-server-image:latest .

      - name: Docker login
        run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Docker push
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/html-server-image:latest
